services:
  - type: web
    name: todo-app
    env: python
    plan: free
    buildCommand: |
      cd backend && pip install -r requirements.txt && \
      cd ../frontend && npm install && VITE_API_URL=/ npm run build && \
      cd ..
    startCommand: |
      cd backend && gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: ALLOWED_ORIGINS
        value: https://todo-app-yfby.onrender.com,http://localhost:3000,http://localhost:5173
